characters = [
    "Mario",
    "Donkey Kong",
    "Link",
    "Samus",
    "Dark Samus",
    "Yoshi",
    "Kirby",
    "Fox",
    "Pikachu",
    "Luigi",
    "Ness",
    "Captain Falcon",
    "Jigglypuff",
    "Peach",
    "Daisy",
    "Bowser",
    "Ice Climbers",
    "Sheik",
    "Zelda",
    "Dr. Mario",
    "Pichu",
    "Falco",
    "Marth",
    "Lucina",
    "Young Link",
    "Ganondorf",
    "Mewtwo",
    "Roy",
    "Chrom",
    "Mr. Game & Watch",
    "Meta Knight",
    "Pit",
    "Dark Pit",
    "Zero Suit Samus",
    "Wario",
    "Snake",
    "Ike",
    "Pokémon Trainer",
    "Squirtle",
    "Ivysaur",
    "Charizard",
    "Diddy Kong",
    "Lucas",
    "Sonic",
    "King Dedede",
    "Olimar",
    "Alph"
    "Lucario",
    "R.O.B.",
    "Toon Link",
    "Wolf",
    "Villager",
    "Mega Man",
    "Wii Fit Trainer",
    "Rosalina & Luma",
    "Little Mac",
    "Greninja",
    "Mii Fighter Brawler",
    "Mii Fighter Swordfighter",
    "Mii Fighter Gunner",
    "Palutena",
    "Pac-Man",
    "Robin",
    "Shulk",
    "Bowser Jr.",
    "Duck Hunt Duo",
    "Ryu",
    "Ken",
    "Cloud",
    "Corrin",
    "Bayonetta",
    "Inkling",
    "Ridley",
    "Simon",
    "Richter",
    "King K. Rool",
    "Isabelle",
    "Incineroar",
    "Piranha Plant",
    "Joker",
    "Hero",
    "Banjo & Kazooie",
    "Terry",
    "Byleth",
    "Min Min",
    "Steve / Alex",
    "Sephiroth",
    "Pyra / Mythra",
    "Kazuya",
    "Sora"
]

normalized_characters = ['mario', 'donkey kong', 'link', 'samus', 'dark samus', 'yoshi', 'kirby', 'fox', 'pikachu', 'luigi', 'ness', 'captain falcon', 'jigglypuff', 'peach', 'daisy', 'bowser', 'ice climbers', 'sheik', 'zelda', 'dr mario', 'pichu', 'falco', 'marth', 'lucina', 'young link', 'ganondorf', 'mewtwo', 'roy', 'chrom', 'mr game watch', 'meta knight', 'pit', 'dark pit', 'zero suit samus', 'wario', 'snake', 'ike', 'pokmon trainer', 'squirtle', 'ivysaur', 'charizard', 'diddy kong', 'lucas', 'sonic', 'king dedede', 'olimar', 'alph', 'lucario', 'rob', 'toon link', 'wolf', 'villager', 'mega man', 'wii fit trainer', 'rosalina luma', 'little mac', 'greninja', 'mii fighter brawler', 'mii fighter swordfighter', 'mii fighter gunner', 'palutena', 'pacman', 'robin', 'shulk', 'bowser jr', 'duck hunt duo', 'ryu', 'ken', 'cloud', 'corrin', 'bayonetta', 'inkling', 'ridley', 'simon', 'richter', 'king k rool', 'isabelle', 'incineroar', 'piranha plant', 'joker', 'hero', 'banjo kazooie', 'terry', 'byleth', 'min min', 'steve alex', 'sephiroth', 'pyra mythra', 'kazuya', 'sora']